## pluck out the peaks with the motifs you care about:
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif1.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif1_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif2.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif2_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif3.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif3_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif4.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif4_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif5.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif5_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_AHF_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/AHF_motif_output/homerResults/motif6.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/AHF/AHF_motif6_outputfile.txt

annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif1.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif1_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif2.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif2_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif3.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif3_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif4.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif4_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif5.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif5_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_PharyngealMesoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/PharyngealMesoderm_motif_output/homerResults/motif6.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/PharyngealMesoderm/PharyngealMesoderm_motif6_outputfile.txt

annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif1.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif1_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif2.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif2_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif3.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif3_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif4.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif4_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif5.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif5_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Endoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Endoderm_motif_output/homerResults/motif6.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Endoderm/Endoderm_motif6_outputfile.txt

annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif1.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif1_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif2.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif2_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif3.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif3_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif4.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif4_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif5.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif5_outputfile.txt
annotatePeaks.pl /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/markerList_Ectoderm_df_homer_trim.bed.txt mm10 -m /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/Ectoderm_motif_output/homerResults/motif6.motif > /Users/sranade/scATAC-seq/Tbx1_E925/DAR_homer/motif_peaks/Ectoderm/Ectoderm_motif6_outputfile.txt
